### ISSUE TITLE
Add Tags for Release Versions

### ISSUE THREAD

**Issue by asayler** [trampgeek/moodle-qbehaviour_adaptive_adapted_for_coderunner#1]
Would it be possible to tag the release versions of this repo in git? This makes it much simpler to clone a specific version of the repo and eases the burden of downstream release management, especially for those of us building Moodle installs via scripts (e.g. for Docker).

E.g.
Running:

```
git tag 2016020100 76bc6b3b6869b36a910e00a9066599976f31f65b
git push --tags
```

Allows one to replace:

```
git clone --recursive --single-branch \
"https://github.com/trampgeek/moodle-qbehaviour_adaptive_adapted_for_coderunner.git" \
"${MOODLE_CODE_PATH}/question/behaviour/adaptive_adapted_for_coderunner" \
&& cd "${MOODLE_CODE_PATH}/question/behaviour/adaptive_adapted_for_coderunner" \
&& git checkout 76bc6b3b6869b36a910e00a9066599976f31f65b \
&& cd
```

With the cleaner:

```
git clone --recursive --single-branch -b 2016020100 \
"https://github.com/trampgeek/moodle-qbehaviour_adaptive_adapted_for_coderunner.git" \
"${MOODLE_CODE_PATH}/question/behaviour/adaptive_adapted_for_coderunner"
```

I'd file this as a pull quest, but github does not currently allow importing git metadata such as tags via pull request -- tags can only be applied by someone with commit access to the repo itself.

**Comment by trampgeek** [comment]
Closing as tags added a year or more ago.
