### ISSUE TITLE
Correct name for moodle-qbehaviour_adaptive_adapted_for_coderunner-* folder?

### ISSUE THREAD

**Issue by dave559** [trampgeek/moodle-qbehaviour_adaptive_adapted_for_coderunner#5]
The installation instructions:
http://coderunner.org.nz/mod/book/view.php?id=184&chapterid=684
in numbered paragraph 1 say: 

"Similarly download the zip file of the required question behaviour from the behaviour github repository, unzip it into the directory moodle/question/behaviour and change the newly-created directory name to **qbehaviour_adaptive_adapted_for_coderunner**."

Numbered paragraph 2 says that the folder should be renamed to "adaptive_adapted_for_coderunner",
as does: 
https://github.com/trampgeek/moodle-qbehaviour_adaptive_adapted_for_coderunner/blob/master/Readme.md

Am I right to assume that "adaptive_adapted_for_coderunner" is the name that the folder should ultimately have, and, if so, could the "formal" documentation be corrected?

**Comment by trampgeek** [comment]
Thanks for taking the time to report this, Dave. Much appreciated. Fixed on coderunner.org.nz and will be updated on github on the next push.
