### ISSUE TITLE
GDPR Implementation

### ISSUE THREAD

**Issue by nashtechdev01** [trampgeek/moodle-qbehaviour_adaptive_adapted_for_coderunner#8]
Hi @trampgeek,

- Our clients are using this behaviour and implemented GDPR for other plugin.Do you have plan to implement GDPR for this plugin ?
- If you don't have any plan to implement it,can we create a pull request to implement it ?

Many thanks,

**Comment by trampgeek** [comment]
OK, GDPR is now implemented in latest version (1.3.5), pushed to github and Moodle plugin repository on 4/8/18.
